# Generated by Django 4.0 on 2022-03-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_forum_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('Spor', 'Spor'), ('MMA', 'MMA'), ('Diğer', 'Diğer')], max_length=10),
        ),
    ]
