# Generated by Django 4.0 on 2022-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_forum_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='username',
            field=models.CharField(default=2, max_length=160),
            preserve_default=False,
        ),
    ]
