# Generated by Django 4.0 on 2022-04-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='arkaplan_foto',
            field=models.ImageField(blank=True, null=True, upload_to='arkaplan_foto'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profil_foto',
            field=models.ImageField(blank=True, null=True, upload_to='profil_foto'),
        ),
    ]
