# Generated by Django 4.0 on 2022-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profil_arkaplan_foto_alter_profil_profil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='username',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
