# Generated by Django 4.0 on 2022-04-10 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profil_guncelle_profil_olusturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumyanit',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.forum'),
        ),
    ]
