# Generated by Django 4.0 on 2022-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_forumyanit_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumyanit',
            name='username',
            field=models.CharField(default=2, max_length=160),
            preserve_default=False,
        ),
    ]
