# Generated by Django 4.0 on 2022-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_forumyanit_cevaba_cevap_profil_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumyanit',
            name='url',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
