# Generated by Django 4.0 on 2022-04-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_forumyanit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='arkaplan_foto',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profil_foto',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
