# Generated by Django 4.0 on 2022-04-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_profil_arkaplan_foto_alter_profil_profil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumyanit',
            name='url',
        ),
    ]
