# Generated by Django 4.0 on 2022-05-06 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_alter_forum_baslik_alter_forum_soru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='goruldu',
        ),
        migrations.AddField(
            model_name='forum',
            name='reforumie',
            field=models.ManyToManyField(blank=True, default=None, related_name='reforumie', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumyanit',
            name='reforumie',
            field=models.ManyToManyField(blank=True, default=None, related_name='reforumie1', to=settings.AUTH_USER_MODEL),
        ),
    ]
