# Generated by Django 4.0 on 2022-06-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_anketsoru_aciklama_anketsoru_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketsoru',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profil'),
        ),
    ]
