# Generated by Django 4.0 on 2022-06-11 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_anketsoru_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketsoru',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu', to=settings.AUTH_USER_MODEL),
        ),
    ]
