# Generated by Django 4.0 on 2022-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_anketcevap_anketsoru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketcevap',
            name='soru10cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru11cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru12cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru13cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru14cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru15cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru16cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru17cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru18cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru19cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru20cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru2cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru3cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru4cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru5cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru6cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru7cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru8cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru9cevap1',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=5, null=True),
        ),
    ]
