# Generated by Django 4.0 on 2022-06-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_anketcevap_soru10cevap1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketcevap',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.profil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru10cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru11cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru12cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru13cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru14cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru15cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru16cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru17cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru18cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru19cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru1cevap1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru20cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru2cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru3cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru4cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru5cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru6cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru7cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru8cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='anketcevap',
            name='soru9cevap1',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10, null=True),
        ),
    ]
