# Generated by Django 4.0 on 2022-03-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='updated',
            new_name='guncelle',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='created',
            new_name='olusturma',
        ),
        migrations.RenameField(
            model_name='forumyanit',
            old_name='updated',
            new_name='guncelle',
        ),
        migrations.RenameField(
            model_name='forumyanit',
            old_name='created',
            new_name='olusturma',
        ),
        migrations.AddField(
            model_name='forum',
            name='baslik_slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
