# Generated by Django 4.0 on 2022-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_updated_forum_guncelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.CharField(choices=[('Spor', 'Spor'), ('Combat', 'Combat'), ('Diğer', 'Diğer')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
