# Generated by Django 4.0 on 2022-03-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_forum_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='baslik_slug',
            field=models.SlugField(),
        ),
    ]
