# Generated by Django 4.0 on 2022-04-01 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0007_alter_forum_baslik_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_foto', models.ImageField(upload_to='profil_foto')),
                ('arkaplan_foto', models.ImageField(upload_to='arkaplan_foto')),
                ('biyografi', models.CharField(blank=True, max_length=160, null=True)),
                ('username_slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
