# Generated by Django 4.0 on 2022-04-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_profil_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumyanit',
            name='user',
        ),
        migrations.AddField(
            model_name='forum',
            name='profil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.profil'),
        ),
        migrations.AddField(
            model_name='forumyanit',
            name='profil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.profil'),
            preserve_default=False,
        ),
    ]
