# Generated by Django 4.0 on 2022-04-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_forumyanit_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumyanit',
            name='cevaba_cevap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.forumyanit'),
            preserve_default=False,
        ),
    ]
