# Generated by Django 4.0 on 2022-04-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_forumyanit_cevaba_cevap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumyanit',
            name='cevaba_cevap',
        ),
    ]
