# Generated by Django 4.0 on 2022-04-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_forumyanit_cevaba_cevap'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumyanit',
            name='cevaba_cevap_profil_username',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
