# Generated by Django 4.0 on 2022-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_forumyanit_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumyanit',
            name='url',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
