# Generated by Django 4.0 on 2022-04-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_profil_arkaplan_foto_alter_profil_profil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='arkaplan_foto',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profil_foto',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
