# Generated by Django 4.0 on 2022-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_forum_dislikes_forum_likes_forumyanit_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='biyografi',
            field=models.CharField(blank=True, default='', max_length=160, null=True),
        ),
    ]
