# Generated by Django 4.0 on 2022-04-26 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_alter_profil_biyografi'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='goruldu',
            field=models.ManyToManyField(blank=True, default=None, related_name='goruldu', to=settings.AUTH_USER_MODEL),
        ),
    ]
