# Generated by Django 4.0 on 2022-05-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_forum_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='baslik',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='forum',
            name='soru',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='forumyanit',
            name='cevap',
            field=models.CharField(max_length=400),
        ),
    ]
