# Generated by Django 4.0 on 2022-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_anketcevap_soru10cevap2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketsoru',
            name='baslik',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
