# Generated by Django 4.0 on 2022-06-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_anketsoru_soru10cevap1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketsoru',
            name='guncelle',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='anketsoru',
            name='olusturma',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
