# Generated by Django 4.0 on 2022-06-11 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0035_anketsoru_guncelle_anketsoru_olusturma'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketsoru',
            name='aciklama',
            field=models.CharField(default=1, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anketsoru',
            name='dislikes',
            field=models.ManyToManyField(blank=True, default=None, related_name='dislikes2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anketsoru',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes2', to=settings.AUTH_USER_MODEL),
        ),
    ]
