# Generated by Django 4.0 on 2022-06-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_anketsoru_goruldu'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketcevap',
            name='anketsoru',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.anketsoru'),
            preserve_default=False,
        ),
    ]
